# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Protobuf.humidifier_pb2 as humidifier__pb2


class HumidifierStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OnOffHumidifier = channel.unary_unary(
                '/SmartOffice.Humidifier/OnOffHumidifier',
                request_serializer=humidifier__pb2.RequestHumidifier.SerializeToString,
                response_deserializer=humidifier__pb2.ResponseHumidifier.FromString,
                )
        self.UpperHumid = channel.unary_unary(
                '/SmartOffice.Humidifier/UpperHumid',
                request_serializer=humidifier__pb2.RequestHumidifier.SerializeToString,
                response_deserializer=humidifier__pb2.ResponseHumidifier.FromString,
                )
        self.LowerHumid = channel.unary_unary(
                '/SmartOffice.Humidifier/LowerHumid',
                request_serializer=humidifier__pb2.RequestHumidifier.SerializeToString,
                response_deserializer=humidifier__pb2.ResponseHumidifier.FromString,
                )
        self.GetHumidifierInfo = channel.unary_unary(
                '/SmartOffice.Humidifier/GetHumidifierInfo',
                request_serializer=humidifier__pb2.RequestHumidifier.SerializeToString,
                response_deserializer=humidifier__pb2.ResponseHumidifier.FromString,
                )
        self.OnOffHumiditySensor = channel.unary_unary(
                '/SmartOffice.Humidifier/OnOffHumiditySensor',
                request_serializer=humidifier__pb2.RequestHumidifier.SerializeToString,
                response_deserializer=humidifier__pb2.ResponseHumidifier.FromString,
                )


class HumidifierServicer(object):
    """Missing associated documentation comment in .proto file."""

    def OnOffHumidifier(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpperHumid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LowerHumid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHumidifierInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnOffHumiditySensor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HumidifierServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OnOffHumidifier': grpc.unary_unary_rpc_method_handler(
                    servicer.OnOffHumidifier,
                    request_deserializer=humidifier__pb2.RequestHumidifier.FromString,
                    response_serializer=humidifier__pb2.ResponseHumidifier.SerializeToString,
            ),
            'UpperHumid': grpc.unary_unary_rpc_method_handler(
                    servicer.UpperHumid,
                    request_deserializer=humidifier__pb2.RequestHumidifier.FromString,
                    response_serializer=humidifier__pb2.ResponseHumidifier.SerializeToString,
            ),
            'LowerHumid': grpc.unary_unary_rpc_method_handler(
                    servicer.LowerHumid,
                    request_deserializer=humidifier__pb2.RequestHumidifier.FromString,
                    response_serializer=humidifier__pb2.ResponseHumidifier.SerializeToString,
            ),
            'GetHumidifierInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHumidifierInfo,
                    request_deserializer=humidifier__pb2.RequestHumidifier.FromString,
                    response_serializer=humidifier__pb2.ResponseHumidifier.SerializeToString,
            ),
            'OnOffHumiditySensor': grpc.unary_unary_rpc_method_handler(
                    servicer.OnOffHumiditySensor,
                    request_deserializer=humidifier__pb2.RequestHumidifier.FromString,
                    response_serializer=humidifier__pb2.ResponseHumidifier.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SmartOffice.Humidifier', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Humidifier(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OnOffHumidifier(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SmartOffice.Humidifier/OnOffHumidifier',
            humidifier__pb2.RequestHumidifier.SerializeToString,
            humidifier__pb2.ResponseHumidifier.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpperHumid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SmartOffice.Humidifier/UpperHumid',
            humidifier__pb2.RequestHumidifier.SerializeToString,
            humidifier__pb2.ResponseHumidifier.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LowerHumid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SmartOffice.Humidifier/LowerHumid',
            humidifier__pb2.RequestHumidifier.SerializeToString,
            humidifier__pb2.ResponseHumidifier.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetHumidifierInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SmartOffice.Humidifier/GetHumidifierInfo',
            humidifier__pb2.RequestHumidifier.SerializeToString,
            humidifier__pb2.ResponseHumidifier.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OnOffHumiditySensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SmartOffice.Humidifier/OnOffHumiditySensor',
            humidifier__pb2.RequestHumidifier.SerializeToString,
            humidifier__pb2.ResponseHumidifier.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
