# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Protobuf.message_pb2 as message__pb2


class GreeterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OnLamp = channel.unary_unary(
                '/SmartOffice.Greeter/OnLamp',
                request_serializer=message__pb2.Request.SerializeToString,
                response_deserializer=message__pb2.Response.FromString,
                )
        self.OffLamp = channel.unary_unary(
                '/SmartOffice.Greeter/OffLamp',
                request_serializer=message__pb2.Request.SerializeToString,
                response_deserializer=message__pb2.Response.FromString,
                )
        self.OnAirCond = channel.unary_unary(
                '/SmartOffice.Greeter/OnAirCond',
                request_serializer=message__pb2.Request.SerializeToString,
                response_deserializer=message__pb2.Response.FromString,
                )
        self.OffAirCond = channel.unary_unary(
                '/SmartOffice.Greeter/OffAirCond',
                request_serializer=message__pb2.Request.SerializeToString,
                response_deserializer=message__pb2.Response.FromString,
                )


class GreeterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def OnLamp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OffLamp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnAirCond(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OffAirCond(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OnLamp': grpc.unary_unary_rpc_method_handler(
                    servicer.OnLamp,
                    request_deserializer=message__pb2.Request.FromString,
                    response_serializer=message__pb2.Response.SerializeToString,
            ),
            'OffLamp': grpc.unary_unary_rpc_method_handler(
                    servicer.OffLamp,
                    request_deserializer=message__pb2.Request.FromString,
                    response_serializer=message__pb2.Response.SerializeToString,
            ),
            'OnAirCond': grpc.unary_unary_rpc_method_handler(
                    servicer.OnAirCond,
                    request_deserializer=message__pb2.Request.FromString,
                    response_serializer=message__pb2.Response.SerializeToString,
            ),
            'OffAirCond': grpc.unary_unary_rpc_method_handler(
                    servicer.OffAirCond,
                    request_deserializer=message__pb2.Request.FromString,
                    response_serializer=message__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SmartOffice.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OnLamp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SmartOffice.Greeter/OnLamp',
            message__pb2.Request.SerializeToString,
            message__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OffLamp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SmartOffice.Greeter/OffLamp',
            message__pb2.Request.SerializeToString,
            message__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OnAirCond(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SmartOffice.Greeter/OnAirCond',
            message__pb2.Request.SerializeToString,
            message__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OffAirCond(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SmartOffice.Greeter/OffAirCond',
            message__pb2.Request.SerializeToString,
            message__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
